import { StyleSheet } from 'react-native';


const styles = StyleSheet.create( {
  main_04:{
    marginTop:40*vw
  },
  roleForJok:{
    color:'#cbcac9',
    fontSize:26*vw,
    width:145*vw,
  },
  roleText:{
    color:'#ffffff',
    fontSize:25*vw,
    fontWeight:'bold',
    width:145*vw,
  

  },
  roleBrand:{
    marginLeft:20*vw,
    marginTop:20*vw
  },
  roleImg:{
    borderRadius:10*vw,
    width:145*vw,
    height:200*vw
  },
  roleMore:{
    color:'#cbcbc9',
    fontSize:26*vw
  },
  roleTitle:{
    fontWeight:'bold',
    fontSize:32*vw,
    color:'#ffffff'
  },
  roleBox:{
    flexDirection:'row',
    paddingLeft:30*vw,
    paddingRight:30*vw,
    justifyContent:'space-between'
  },
  sideContent:{
    height:1.5*vh,
    width:300,
    backgroundColor:'#cccccc'
  },
  topBox:{
    marginTop:20*vw,

    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between'
  },
  titleCount:{
    fontSize:26*vw,
    fontWeight:'normal',
  },
  topTitle:{
    fontWeight:'bold',
    fontSize:30*vw,
    marginLeft:30*vw,
    borderBottomColor:'#000',
    borderBottomWidth:2
  },
  topBar:{
    width:64*vw,
    height:10*vw,
    borderRadius:5*vw,
    backgroundColor:'#dadad6',
    marginLeft:343*vw,
    marginTop:20*vw
  },
  mainSlide:{
    position:'absolute',
    top:0.8*vh,
    width:'100%',
  },
  slideBox:{
    height:'100%',
    backgroundColor:'#f8f8f4',
    width:'100%',
    borderTopLeftRadius:20*vw,
    borderTopRightRadius:20*vw,

  },
  slideTop:{
    height:60,
  },
 
  countTitle:{
    color:'#ffffff',
    fontWeight:'bold',
    marginTop:20*vw,
    marginLeft:20*vw,
    fontSize:24*vw
  },
  main_02:{
    width:690*vw,
    marginLeft:30*vw,
    marginTop:30*vw,
    borderRadius:10,
    backgroundColor:'#656461',
    height:210*vw
  },
  btnBox:{
    flexDirection:'row',
  },
  flexRow:{
    flexDirection:'row',
    flexWrap:'wrap',
    width:480*vw
  },
  main_01:{
    paddingLeft:30*vw,
    paddingRight:30*vw,
    paddingTop:20*vw
  },
  body:{
    backgroundColor:'#9e9d98',
    flex:1
  },
  movieImg:{
    width:180*vw,
    height:250*vw,
    borderRadius:10,
    marginRight:30*vw
  },
  movieBrand:{
    flexDirection:'row',
    paddingRight:30*vw,
    alignItems:'center',
    justifyContent:'space-between'
  },
  movieEditor:{
    flexDirection:'row',
    color:'#ffffff',
    fontWeight:'bold',

  },
  movieTitle:{
    color:'#ffffff',
    fontWeight:'bold',
    fontSize:32*vw,
    width:480*vw,
    flexWrap:'wrap'
  },
  star:{
    height:40*vw,
    width:40*vw
  },
  btn:{
    height:50*vw,
    width:150*vw,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'#ffffff',
    borderRadius:5,
    flexDirection:'row',
    marginTop:20*vw,
  },
  movieText:{
    color:'#ffffff',
    fontSize:24*vw,
    fontWeight:'bold'
  },
  movie_t:{
    color:'#c8c7c5',
    fontSize:20*vw
  } ,
  countBox:{
    flexDirection:'row',
  },
  starRow:{
    flexDirection:'row',
    marginTop:10*vw
  },
  countText:{
    fontSize:36*vw,
    color:'#FFFFFF',
    fontWeight:'bold',
    textAlign:'center'
  },
  contImg:{
    width:25*vw,
    height:25*vw
  },
  countBrand:{
    width:110*vw,
    justifyContent:'center',
    marginLeft:60*vw,
    marginTop:20*vw
  },
  listCountImgBox:{
    width:80*vw,
    flexDirection:'row-reverse'
  },
  starList:{
    flexDirection:'row',
    alignItems:'center'
  },
  starBox:{
    marginLeft:60*vw,
  },
  scrollBrand:{
    backgroundColor:'#656461',
    color:'#ffffff',
    paddingLeft:20*vw,
    paddingRight:20*vw,
    paddingTop:10*vw,
    paddingBottom:10*vw,
    borderRadius:6,
    marginRight:20*vw
  },
  main_03:{
    marginTop:30*vw
  },
  csrollBox:{
    paddingBottom:5,
  }

})
export default styles